import type { Approval, Mission } from "./types";

export const MOCK_MISSIONS: Mission[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    title: "Quarterly offsite planning",
    description: "Venue search, agenda, and stakeholder comms.",
    status: "active",
    priority: "normal",
    created_by: "command_center",
    surface_origin: "command_center",
    risk_class: "green",
    current_stage: "execution",
    summary: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    title: "Security review for new integration",
    description: "Awaiting human approval for production rollout.",
    status: "awaiting_approval",
    priority: "high",
    created_by: "api",
    surface_origin: "api",
    risk_class: "amber",
    current_stage: "review",
    summary: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    title: "Weekly metrics digest",
    description: "Automated report generation.",
    status: "complete",
    priority: "low",
    created_by: "voice",
    surface_origin: "voice",
    risk_class: null,
    current_stage: null,
    summary: "Completed successfully.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_APPROVALS: Approval[] = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    mission_id: "00000000-0000-4000-8000-000000000002",
    action_type: "Book a conference center",
    risk_class: "amber",
    reason: "High spend threshold",
    command_text: null,
    dashclaw_decision_id: null,
    status: "pending",
    requested_by: "jarvis",
    requested_via: "command_center",
    decided_by: null,
    decided_via: null,
    decision_notes: null,
    created_at: new Date().toISOString(),
    decided_at: null,
    expires_at: null,
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    mission_id: "00000000-0000-4000-8000-000000000001",
    action_type: "Send external email blast",
    risk_class: "red",
    reason: "PII exposure risk",
    command_text: null,
    dashclaw_decision_id: null,
    status: "pending",
    requested_by: "operator",
    requested_via: "sms",
    decided_by: null,
    decided_via: null,
    decision_notes: null,
    created_at: new Date().toISOString(),
    decided_at: null,
    expires_at: null,
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    mission_id: "00000000-0000-4000-8000-000000000003",
    action_type: "Enable new tool integration",
    risk_class: "green",
    reason: null,
    command_text: null,
    dashclaw_decision_id: null,
    status: "approved",
    requested_by: "operator",
    requested_via: "voice",
    decided_by: "lead",
    decided_via: "command_center",
    decision_notes: "Approved for pilot.",
    created_at: new Date().toISOString(),
    decided_at: new Date().toISOString(),
    expires_at: null,
  },
];
